sudo: required
dist: trusty
language: python
python: 3.5

# use cache for big builds like pandas
cache:
  pip: true
  directories:
    - $HOME/.cache/pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

notifications:
  email: false
# branches:  # remove travis double-check on pull requests in main repo
#   only:
#     - master
#     - /^\d\.\d+$/

env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=pypy
  - TOXENV=pypy3
  - TOXENV=flake8
  - TOXENV=perf

before_install:
  # fix a crash with multiprocessing on Travis
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
  # install codecov
  - pip install codecov

install:
  # install big packages (they are cached to minimize build time)
  # if issues, clear cache
  # https://docs.travis-ci.com/user/caching/#Clearing-Caches
  - pip install pandas
  # Coverage install
  # - pip install tox 'coverage<4' coveralls
  - pip install tox 'coverage<4'
  # install this package (tqdm) into the environment
  - python setup.py install

# run tests
script:
  - tox

# submit coverage
after_success:
  # - coveralls
  - codecov
